version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
     - 3000:3000

  redis:
    container_name: rts
    image: redislabs/redistimeseries
    ports:
      - 6379:6379
  
  test-server:
    container_name: test-server
    image: ghcr.io/slntopp/rts-traffic-data-source:latest
    environment:
      REDIS_HOST: redis://rts:6379
    ports:
      - 8000:8000