// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rts_traffic_data_source

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrafanaJSONDataSourceServiceClient is the client API for GrafanaJSONDataSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrafanaJSONDataSourceServiceClient interface {
	Test(ctx context.Context, in *TestR, opts ...grpc.CallOption) (*TestR, error)
}

type grafanaJSONDataSourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrafanaJSONDataSourceServiceClient(cc grpc.ClientConnInterface) GrafanaJSONDataSourceServiceClient {
	return &grafanaJSONDataSourceServiceClient{cc}
}

func (c *grafanaJSONDataSourceServiceClient) Test(ctx context.Context, in *TestR, opts ...grpc.CallOption) (*TestR, error) {
	out := new(TestR)
	err := c.cc.Invoke(ctx, "/grafana.json_datasource.GrafanaJSONDataSourceService/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrafanaJSONDataSourceServiceServer is the server API for GrafanaJSONDataSourceService service.
// All implementations must embed UnimplementedGrafanaJSONDataSourceServiceServer
// for forward compatibility
type GrafanaJSONDataSourceServiceServer interface {
	Test(context.Context, *TestR) (*TestR, error)
	mustEmbedUnimplementedGrafanaJSONDataSourceServiceServer()
}

// UnimplementedGrafanaJSONDataSourceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGrafanaJSONDataSourceServiceServer struct {
}

func (UnimplementedGrafanaJSONDataSourceServiceServer) Test(context.Context, *TestR) (*TestR, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedGrafanaJSONDataSourceServiceServer) mustEmbedUnimplementedGrafanaJSONDataSourceServiceServer() {
}

// UnsafeGrafanaJSONDataSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrafanaJSONDataSourceServiceServer will
// result in compilation errors.
type UnsafeGrafanaJSONDataSourceServiceServer interface {
	mustEmbedUnimplementedGrafanaJSONDataSourceServiceServer()
}

func RegisterGrafanaJSONDataSourceServiceServer(s grpc.ServiceRegistrar, srv GrafanaJSONDataSourceServiceServer) {
	s.RegisterService(&GrafanaJSONDataSourceService_ServiceDesc, srv)
}

func _GrafanaJSONDataSourceService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrafanaJSONDataSourceServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.json_datasource.GrafanaJSONDataSourceService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrafanaJSONDataSourceServiceServer).Test(ctx, req.(*TestR))
	}
	return interceptor(ctx, in, info, handler)
}

// GrafanaJSONDataSourceService_ServiceDesc is the grpc.ServiceDesc for GrafanaJSONDataSourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrafanaJSONDataSourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.json_datasource.GrafanaJSONDataSourceService",
	HandlerType: (*GrafanaJSONDataSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _GrafanaJSONDataSourceService_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/api.proto",
}
